apiVersion: v1
kind: Service
metadata:
  name: sampleserver
  labels:
    app: sampleserver
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: sampleserver